import { sqliteTable, integer, text, real } from 'drizzle-orm/sqlite-core';

export default sqliteTable('setting', {
    settingId: integer('setting_id').primaryKey({ autoIncrement: true }),
    register: integer('register').notNull(),
    receive: integer('receive').notNull(),
    addEmail: integer('add_email').notNull(),
    manyEmail: integer('many_email').notNull(),
    title: text('title').notNull(),
    autoRefresh: integer('auto_refresh').notNull(),
    registerVerify: integer('register_verify').notNull(),
    addEmailVerify: integer('add_email_verify').notNull(),
    resendTokens: text('resend_tokens').notNull().default('{}'),
    send: integer('send').notNull().default(0),
    r2Domain: text('r2_domain'),
    siteKey: text('site_key'),
    secretKey: text('secret_key'),
    background: text('background'),
    loginOpacity: real('login_opacity').notNull().default(0.90),
    tgBotToken: text('tg_bot_token'),
    tgChatId: text('tg_chat_id'),
    tgBotStatus: integer('tg_bot_status').default(1),
    forwardStatus: integer('forward_status').default(1),
    forwardEmail: text('forward_email'),
    ruleType: integer('rule_type').default(0),
    ruleEmail: text('rule_email'),
    noRecipient: integer('no_recipient').default(0),
    customDomain: text('custom_domain'),
    bucket: text('bucket'),
    endpoint: text('endpoint'),
    region: text('region'),
    s3AccessKey: text('s3_access_key'),
    s3SecretKey: text('s3_secret_key'),
    forcePathStyle: integer('force_path_style').default(0),
    maxAccountCount: integer('max_account_count').default(10),
    tgMsgTo: text('tg_msg_to').default('show'),
    tgMsgFrom: text('tg_msg_from').default('show'),
    tgMsgText: text('tg_msg_text').default('show')
});
